package org.idp.server.type;

/** OAuthRequestKey */
public enum OAuthRequestKey {
  scope,
  response_type,
  client_id,
  redirect_uri,
  state,
  response_mode,
  nonce,
  display,
  prompt,
  max_age,
  ui_locales,
  id_token_hint,
  login_hint,
  acr_values,
  claims,
  request,
  request_uri,
  code_challenge,
  code_challenge_method,
  code_verifier,
  code,
  grant_type,
  client_secret,
  token,
  token_type_hint,
  client_assertion,
  client_assertion_type,
  refresh_token,
}
