import { describe, expect, it, beforeAll, afterAll } from "@jest/globals";
import { onboarding } from "../../../api/managementClient";
import { deletion, get, postWithJson } from "../../../lib/http";
import { requestToken, getUserinfo } from "../../../api/oauthClient";
import { generateECP256JWKS, verifyAndDecodeJwt } from "../../../lib/jose";
import { adminServerConfig, backendUrl } from "../../testConfig";
import { v4 as uuidv4 } from "uuid";
import crypto from "crypto";
import { createBearerHeader } from "../../../lib/util";

/**
 * /v1/me Use Case: self-service email change (Issue #1416).
 *
 * Two endpoints, because the two operations carry different privilege and therefore different
 * scope (verification only sets a claim; a change moves the login identifier):
 *   POST /v1/me/email/change             {new_email} -> change tx + code to the new address
 *   POST /v1/me/email/change/{id}/verify  {code}     -> commits the new email
 *   POST /v1/me/email/verification                   -> verify tx + code to the CURRENT address
 *   POST /v1/me/email/verification/{id}/verify {code} -> commits email_verified: true
 * scope: change requires email:change, verification requires openid.
 *
 * The verification code is generated by the idp-server (built-in executor) and read back via the
 * management API; the send step posts to a mock send-email API (docker/mockoon: /email-send).
 *
 * Uniqueness of an identifier is enforced on preferred_username, which the identity policy derives.
 * So the accept/reject of a duplicate email depends on the tenant policy:
 *   - EMAIL     -> preferred_username tracks email  -> change to a taken email is REJECTED
 *   - USERNAME  -> preferred_username tracks name   -> email is a plain attribute, duplicate ALLOWED
 */
const redirectUri =
  "https://www.certification.openid.net/test/a/idp_oidc_basic/callback";

const emailConfigBody = (expireSeconds = 300) => ({
  id: uuidv4(),
  type: "email",
  attributes: {},
  metadata: {
    type: "internal",
    transaction_id_param: "transaction_id",
    verification_code_param: "verification_code",
  },
  interactions: {
    "email-authentication-challenge": {
      request: {
        schema: {
          type: "object",
          properties: { email: { type: "string" }, template: { type: "string" } },
        },
      },
      execution: {
        function: "email_authentication_challenge",
        details: {
          function: "http_request",
          sender: "test@example.com",
          sender_config: {
            http_request: {
              url: "http://host.docker.internal:4000/email-send",
              method: "POST",
              header_mapping_rules: [{ static_value: "application/json", to: "Content-Type" }],
              body_mapping_rules: [{ from: "$.request_body", to: "*" }],
            },
          },
          templates: {
            authentication: { subject: "Login code", body: "Code: {VERIFICATION_CODE}" },
            email_change: {
              subject: "Email change confirmation",
              body: "You requested an email change. Code: {VERIFICATION_CODE}",
            },
            email_verify: {
              subject: "Email verification",
              body: "Confirm your email address. Code: {VERIFICATION_CODE}",
            },
          },
          retry_count_limitation: 5,
          expire_seconds: expireSeconds,
        },
      },
      response: { body_mapping_rules: [{ from: "$.response_body", to: "*" }] },
    },
    "email-authentication": {
      request: {
        schema: { type: "object", properties: { verification_code: { type: "string" } } },
      },
      execution: { function: "email_authentication" },
      response: {
        // Built-in executor errors surface as flat {error, error_description}; map them only when
        // present so the success response is not polluted with null error fields.
        body_mapping_rules: [
          { from: "$.error", to: "error", condition: { operation: "exists", path: "$.error" } },
          {
            from: "$.error_description",
            to: "error_description",
            condition: { operation: "exists", path: "$.error_description" },
          },
        ],
      },
    },
  },
});

const confirmPolicyBody = (flow) => ({
  id: uuidv4(),
  flow,
  enabled: true,
  policies: [
    {
      description: `self_service_${flow}`,
      priority: 1,
      conditions: {},
      available_methods: ["email"],
      step_definitions: [{ method: "email", order: 1, requires_user: true }],
      success_conditions: {
        any_of: [
          [{ path: "$.email-confirm.success_count", type: "integer", operation: "gte", value: 1 }],
        ],
      },
    },
  ],
});

/** Onboards a tenant with the given identity policy and registers the email + change configs. */
async function provisionTenant(systemAccessToken, identityUniqueKeyType, { expireSeconds = 300 } = {}) {
  const timestamp = `${Date.now()}-${crypto.randomBytes(3).toString("hex")}`;
  const ctx = {
    organizationId: uuidv4(),
    tenantId: uuidv4(),
    clientId: uuidv4(),
    clientSecret: `client-secret-${crypto.randomBytes(16).toString("hex")}`,
    adminName: `admin-${timestamp}`,
    adminEmail: `admin-${timestamp}@me-change.example.com`,
    adminPassword: `AdminPass_${timestamp}!`,
  };
  const jwksContent = await generateECP256JWKS();

  const onboardingResponse = await onboarding({
    body: {
      organization: { id: ctx.organizationId, name: `Me Org ${timestamp}`, description: "e2e" },
      tenant: {
        id: ctx.tenantId,
        name: `Me Tenant ${timestamp}`,
        domain: backendUrl,
        authorization_provider: "idp-server",
        identity_policy_config: { identity_unique_key_type: identityUniqueKeyType },
        session_config: { cookie_name: `ME_${timestamp}`, use_secure_cookie: false },
        cors_config: { allow_origins: [backendUrl] },
        security_event_log_config: {
          format: "structured_json",
          stage: "processed",
          include_user_id: true,
          include_ip: true,
          include_detail: true,
          persistence_enabled: true,
        },
      },
      authorization_server: {
        issuer: `${backendUrl}/${ctx.tenantId}`,
        authorization_endpoint: `${backendUrl}/${ctx.tenantId}/v1/authorizations`,
        token_endpoint: `${backendUrl}/${ctx.tenantId}/v1/tokens`,
        token_endpoint_auth_methods_supported: ["client_secret_post"],
        userinfo_endpoint: `${backendUrl}/${ctx.tenantId}/v1/userinfo`,
        jwks_uri: `${backendUrl}/${ctx.tenantId}/v1/jwks`,
        jwks: jwksContent,
        grant_types_supported: ["authorization_code", "refresh_token", "password"],
        token_signed_key_id: "signing_key_1",
        id_token_signed_key_id: "signing_key_1",
        scopes_supported: ["openid", "profile", "email", "email:change", "management", "org-management"],
        claims_supported: ["sub", "iss", "name", "email", "email_verified"],
        response_types_supported: ["code"],
        response_modes_supported: ["query"],
        subject_types_supported: ["public"],
        id_token_signing_alg_values_supported: ["ES256"],
        extension: { access_token_type: "JWT" },
      },
      user: {
        sub: uuidv4(),
        provider_id: "idp-server",
        name: ctx.adminName,
        preferred_username: identityUniqueKeyType === "EMAIL" ? ctx.adminEmail : ctx.adminName,
        email: ctx.adminEmail,
        email_verified: true,
        raw_password: ctx.adminPassword,
      },
      client: {
        client_id: ctx.clientId,
        client_secret: ctx.clientSecret,
        redirect_uris: [redirectUri],
        response_types: ["code"],
        grant_types: ["authorization_code", "refresh_token", "password"],
        scope: "openid profile email email:change management org-management",
        client_name: "Me Client",
        token_endpoint_auth_method: "client_secret_post",
        application_type: "web",
      },
    },
    headers: { Authorization: `Bearer ${systemAccessToken}` },
  });
  if (onboardingResponse.status !== 201) {
    console.error("Onboarding failed:", JSON.stringify(onboardingResponse.data, null, 2));
  }
  expect(onboardingResponse.status).toBe(201);

  const mgmtTokenResponse = await requestToken({
    endpoint: `${backendUrl}/${ctx.tenantId}/v1/tokens`,
    grantType: "password",
    username: identityUniqueKeyType === "EMAIL" ? ctx.adminEmail : ctx.adminName,
    password: ctx.adminPassword,
    scope: "management org-management",
    clientId: ctx.clientId,
    clientSecret: ctx.clientSecret,
  });
  expect(mgmtTokenResponse.status).toBe(200);
  ctx.mgmtAccessToken = mgmtTokenResponse.data.access_token;
  ctx.identityUniqueKeyType = identityUniqueKeyType;

  const emailResp = await postWithJson({
    url: `${backendUrl}/v1/management/organizations/${ctx.organizationId}/tenants/${ctx.tenantId}/authentication-configurations`,
    headers: { Authorization: `Bearer ${ctx.mgmtAccessToken}` },
    body: emailConfigBody(expireSeconds),
  });
  expect(emailResp.status).toBe(201);
  for (const flow of ["email-verify", "email-change"]) {
    const policyResp = await postWithJson({
      url: `${backendUrl}/v1/management/organizations/${ctx.organizationId}/tenants/${ctx.tenantId}/authentication-policies`,
      headers: { Authorization: `Bearer ${ctx.mgmtAccessToken}` },
      body: confirmPolicyBody(flow),
    });
    expect(policyResp.status).toBe(201);
  }

  return ctx;
}

async function createUser(ctx, { name, email, password, emailVerified = true }) {
  const sub = uuidv4();
  const resp = await postWithJson({
    url: `${backendUrl}/v1/management/organizations/${ctx.organizationId}/tenants/${ctx.tenantId}/users`,
    headers: { Authorization: `Bearer ${ctx.mgmtAccessToken}` },
    body: {
      sub,
      provider_id: "idp-server",
      name,
      preferred_username: ctx.identityUniqueKeyType === "EMAIL" ? email : name,
      email,
      email_verified: emailVerified,
      raw_password: password,
      status: "REGISTERED",
    },
  });
  expect(resp.status).toBe(201);
  return sub;
}

const loginIdentifier = (ctx, { name, email }) =>
  ctx.identityUniqueKeyType === "EMAIL" ? email : name;

function passwordGrant(ctx, username, password, scope = "openid") {
  return requestToken({
    endpoint: `${backendUrl}/${ctx.tenantId}/v1/tokens`,
    grantType: "password",
    username,
    password,
    scope,
    clientId: ctx.clientId,
    clientSecret: ctx.clientSecret,
  });
}

/**
 * Reads the code the built-in executor generated. It is stored under the shared
 * email-authentication-challenge key regardless of which flow issued it.
 */
async function readChallengeCode(ctx, transactionId) {
  const interactionResp = await get({
    url: `${backendUrl}/v1/management/organizations/${ctx.organizationId}/tenants/${ctx.tenantId}/authentication-interactions/${transactionId}/email-authentication-challenge`,
    headers: { Authorization: `Bearer ${ctx.mgmtAccessToken}` },
  });
  expect(interactionResp.status).toBe(200);
  return interactionResp.data.payload.verification_code;
}

/** Starts a change and reads the server-generated code, returning both the tx id and the code. */
async function startChange(ctx, accessToken, newEmail) {
  const startResp = await postWithJson({
    url: `${backendUrl}/${ctx.tenantId}/v1/me/email/change`,
    headers: createBearerHeader(accessToken),
    body: { new_email: newEmail },
  });
  expect(startResp.status).toBe(200);
  const transactionId = startResp.data.id;
  return { transactionId, code: await readChallengeCode(ctx, transactionId) };
}

function submitCode(ctx, accessToken, transactionId, code) {
  return postWithJson({
    url: `${backendUrl}/${ctx.tenantId}/v1/me/email/change/${transactionId}/verify`,
    headers: createBearerHeader(accessToken),
    body: { verification_code: code },
  });
}

/** Runs the full change flow, returning the verify response. */
async function runEmailChange(ctx, accessToken, newEmail) {
  const { transactionId, code } = await startChange(ctx, accessToken, newEmail);
  return submitCode(ctx, accessToken, transactionId, code);
}

/** Runs the full verification flow (current address, no body), returning the verify response. */
async function runEmailVerification(ctx, accessToken) {
  const startResp = await postWithJson({
    url: `${backendUrl}/${ctx.tenantId}/v1/me/email/verification`,
    headers: createBearerHeader(accessToken),
    body: {},
  });
  expect(startResp.status).toBe(200);
  const transactionId = startResp.data.id;
  const code = await readChallengeCode(ctx, transactionId);

  return postWithJson({
    url: `${backendUrl}/${ctx.tenantId}/v1/me/email/verification/${transactionId}/verify`,
    headers: createBearerHeader(accessToken),
    body: { verification_code: code },
  });
}

describe("Me Use Case: self-service email change", () => {
  let systemAccessToken;
  const tenants = [];

  beforeAll(async () => {
    const tokenResponse = await requestToken({
      endpoint: adminServerConfig.tokenEndpoint,
      grantType: "password",
      username: adminServerConfig.oauth.username,
      password: adminServerConfig.oauth.password,
      scope: adminServerConfig.adminClient.scope,
      clientId: adminServerConfig.adminClient.clientId,
      clientSecret: adminServerConfig.adminClient.clientSecret,
    });
    expect(tokenResponse.status).toBe(200);
    systemAccessToken = tokenResponse.data.access_token;
  });

  afterAll(async () => {
    for (const ctx of tenants) {
      await deletion({
        url: `${backendUrl}/v1/management/organizations/${ctx.organizationId}/tenants/${ctx.tenantId}`,
        headers: { Authorization: `Bearer ${ctx.mgmtAccessToken}` },
      }).catch(() => {});
      await deletion({
        url: `${backendUrl}/v1/management/orgs/${ctx.organizationId}`,
        headers: { Authorization: `Bearer ${systemAccessToken}` },
      }).catch(() => {});
    }
  });

  it("EMAIL policy: changes email and moves the login identifier to the new address", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);
    const newEmail = `fresh-${Date.now()}@me-change.example.com`;

    const token = await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid email email:change");
    expect(token.status).toBe(200);
    const accessToken = token.data.access_token;

    const verifyResp = await runEmailChange(ctx, accessToken, newEmail);
    expect(verifyResp.status).toBe(200);

    const userinfoResp = await getUserinfo({
      endpoint: `${backendUrl}/${ctx.tenantId}/v1/userinfo`,
      authorizationHeader: createBearerHeader(accessToken),
    });
    expect(userinfoResp.data.email).toBe(newEmail);
    // Integrity: the changed email is marked verified (proof of possession was completed).
    expect(userinfoResp.data.email_verified).toBe(true);

    // A fresh login by the new email works and its id_token reflects the new email.
    const newLogin = await passwordGrant(ctx, newEmail, ctx.adminPassword, "openid email email:change");
    expect(newLogin.status).toBe(200);
    const jwksResp = await get({ url: `${backendUrl}/${ctx.tenantId}/v1/jwks` });
    const { payload } = verifyAndDecodeJwt({ jwt: newLogin.data.id_token, jwks: jwksResp.data });
    expect(payload.email).toBe(newEmail);

    // The old email is no longer a valid login identifier.
    expect((await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword)).status).toBe(400);
  });

  it("EMAIL policy: rejects changing to an email already used by another user", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);

    const otherEmail = `taken-${Date.now()}@me-change.example.com`;
    await createUser(ctx, { name: "Other User", email: otherEmail, password: "OtherPass_1!" });

    const token = await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid email email:change");
    const accessToken = token.data.access_token;

    const verifyResp = await runEmailChange(ctx, accessToken, otherEmail);
    console.log("duplicate(email) verify:", verifyResp.status, JSON.stringify(verifyResp.data));
    expect(verifyResp.status).toBe(400);
    expect(verifyResp.data.error_description).toContain("already in use");

    // The change was rejected, so the admin still logs in with the original email.
    expect((await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword)).status).toBe(200);
  });

  it("code robustness: rejects a wrong verification code and leaves the email unchanged", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);
    const token = (
      await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid email email:change")
    ).data.access_token;

    const { transactionId } = await startChange(
      ctx,
      token,
      `wrong-${Date.now()}@me-change.example.com`
    );
    const resp = await submitCode(ctx, token, transactionId, "000000");
    console.log("wrong code:", resp.status, JSON.stringify(resp.data));
    expect(resp.status).toBe(400);
    expect(resp.data.error_description).toContain("Invalid verification code");

    const userinfo = await getUserinfo({
      endpoint: `${backendUrl}/${ctx.tenantId}/v1/userinfo`,
      authorizationHeader: createBearerHeader(token),
    });
    expect(userinfo.data.email).toBe(ctx.adminEmail);
  });

  it("code robustness: rejects reusing a consumed change transaction", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);
    const token = (
      await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid email email:change")
    ).data.access_token;

    const { transactionId, code } = await startChange(
      ctx,
      token,
      `reuse-${Date.now()}@me-change.example.com`
    );
    expect((await submitCode(ctx, token, transactionId, code)).status).toBe(200);

    const second = await submitCode(ctx, token, transactionId, code);
    console.log("reuse:", second.status, JSON.stringify(second.data));
    expect(second.status).toBe(404);
  });

  it("code robustness: rejects an expired verification code", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL", { expireSeconds: 1 });
    tenants.push(ctx);
    const token = (
      await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid email email:change")
    ).data.access_token;

    const { transactionId, code } = await startChange(
      ctx,
      token,
      `expire-${Date.now()}@me-change.example.com`
    );
    // Let the 1s challenge lapse before verifying, even with the correct code.
    await new Promise((resolve) => setTimeout(resolve, 2000));

    const expired = await submitCode(ctx, token, transactionId, code);
    console.log("expired:", expired.status, JSON.stringify(expired.data));
    expect(expired.status).toBe(400);
    expect(expired.data.error_description).toContain("expired");
  });

  it("code robustness: locks after too many wrong codes", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);
    const token = (
      await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid email email:change")
    ).data.access_token;

    const { transactionId, code } = await startChange(
      ctx,
      token,
      `lock-${Date.now()}@me-change.example.com`
    );
    for (let i = 0; i < 5; i++) {
      expect((await submitCode(ctx, token, transactionId, "000000")).status).toBe(400);
    }
    // Without the lock the correct code would return 200; it is rejected, proving the retry limit.
    const locked = await submitCode(ctx, token, transactionId, code);
    console.log("locked:", locked.status, JSON.stringify(locked.data));
    expect(locked.status).toBe(400);
    expect(locked.data.error_description).toContain("limited");
  });

  it("verification endpoint verifies the current address without changing it", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);

    // A user whose email is not yet verified. Note: only openid — the verification half must not
    // require email:change.
    const email = `unverified-${Date.now()}@me-change.example.com`;
    const password = "UnverifiedPass_1!";
    await createUser(ctx, { name: email, email, password, emailVerified: false });
    const token = (await passwordGrant(ctx, email, password, "openid")).data.access_token;

    const verifyResp = await runEmailVerification(ctx, token);
    console.log("verification:", verifyResp.status, JSON.stringify(verifyResp.data));
    expect(verifyResp.status).toBe(200);

    const userinfo = await getUserinfo({
      endpoint: `${backendUrl}/${ctx.tenantId}/v1/userinfo`,
      authorizationHeader: createBearerHeader(
        (await passwordGrant(ctx, email, password, "openid email")).data.access_token
      ),
    });
    expect(userinfo.data.email).toBe(email);
    expect(userinfo.data.email_verified).toBe(true);

    // Audit: a verification event, not a change event.
    await new Promise((resolve) => setTimeout(resolve, 2000));
    const events = await get({
      url: `${backendUrl}/v1/management/organizations/${ctx.organizationId}/tenants/${ctx.tenantId}/security-events`,
      headers: { Authorization: `Bearer ${ctx.mgmtAccessToken}` },
      params: { limit: 30 },
    });
    const types = events.data.list.map((e) => e.type);
    console.log("verification events:", JSON.stringify(types));
    expect(types).toContain("email_verify_success");
    expect(types).not.toContain("email_change_success");
  });

  it("verification endpoint ignores a caller-supplied new_email", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);
    const token = (await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid")).data
      .access_token;

    // The verification half has no caller-supplied recipient: the body is ignored outright, so it
    // cannot be pointed at an attacker's address even by a token that holds email:change.
    const startResp = await postWithJson({
      url: `${backendUrl}/${ctx.tenantId}/v1/me/email/verification`,
      headers: createBearerHeader(token),
      body: { new_email: `hijack-${Date.now()}@me-change.example.com` },
    });
    expect(startResp.status).toBe(200);

    const code = await readChallengeCode(ctx, startResp.data.id);
    const finish = await postWithJson({
      url: `${backendUrl}/${ctx.tenantId}/v1/me/email/verification/${startResp.data.id}/verify`,
      headers: createBearerHeader(token),
      body: { verification_code: code },
    });
    expect(finish.status).toBe(200);

    // Still the original address, and it is still the login identifier.
    expect((await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword)).status).toBe(200);
  });

  it("change endpoint rejects the current address and points at the verification endpoint", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);
    const token = (
      await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid email email:change")
    ).data.access_token;

    const resp = await postWithJson({
      url: `${backendUrl}/${ctx.tenantId}/v1/me/email/change`,
      headers: createBearerHeader(token),
      body: { new_email: ctx.adminEmail },
    });
    console.log("change-to-same:", resp.status, JSON.stringify(resp.data));
    expect(resp.status).toBe(400);
    expect(resp.data.error_description).toContain("verification endpoint");
  });

  it("security: a token without email:change cannot start or finish a change", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);

    // Start a legitimate change with a properly scoped token...
    const scopedToken = (
      await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid email email:change")
    ).data.access_token;
    const started = await startChange(
      ctx,
      scopedToken,
      `scope-${Date.now()}@me-change.example.com`
    );

    // ...then try both halves with a token that only has openid. Moving the login identifier must
    // not be reachable from an ordinary OIDC token.
    const plainToken = (await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid")).data
      .access_token;

    const startDenied = await postWithJson({
      url: `${backendUrl}/${ctx.tenantId}/v1/me/email/change`,
      headers: createBearerHeader(plainToken),
      body: { new_email: `denied-${Date.now()}@me-change.example.com` },
    });
    console.log("change without scope:", startDenied.status, JSON.stringify(startDenied.data));
    expect(startDenied.status).toBe(403);
    expect(startDenied.data.error).toBe("insufficient_scope");
    expect(startDenied.data.scope).toBe("email:change");

    const finishDenied = await postWithJson({
      url: `${backendUrl}/${ctx.tenantId}/v1/me/email/change/${started.transactionId}/verify`,
      headers: createBearerHeader(plainToken),
      body: { verification_code: started.code },
    });
    console.log("verify without scope:", finishDenied.status, JSON.stringify(finishDenied.data));
    expect(finishDenied.status).toBe(403);
    expect(finishDenied.data.error).toBe("insufficient_scope");

    // The account is untouched.
    expect((await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword)).status).toBe(200);
  });

  it("rejects verifying another user's change transaction (ownership)", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);

    const bEmail = `userb-${Date.now()}@me-change.example.com`;
    const bPassword = "UserBPass_1!";
    await createUser(ctx, { name: "User B", email: bEmail, password: bPassword });

    // User A starts a change and we read A's real code.
    const aToken = (
      await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid email email:change")
    ).data.access_token;
    const startResp = await postWithJson({
      url: `${backendUrl}/${ctx.tenantId}/v1/me/email/change`,
      headers: createBearerHeader(aToken),
      body: { new_email: `a-new-${Date.now()}@me-change.example.com` },
    });
    expect(startResp.status).toBe(200);
    const transactionId = startResp.data.id;
    const interactionResp = await get({
      url: `${backendUrl}/v1/management/organizations/${ctx.organizationId}/tenants/${ctx.tenantId}/authentication-interactions/${transactionId}/email-authentication-challenge`,
      headers: { Authorization: `Bearer ${ctx.mgmtAccessToken}` },
    });
    const code = interactionResp.data.payload.verification_code;

    // User B, even with A's code, cannot drive A's transaction.
    const bToken = (await passwordGrant(ctx, bEmail, bPassword, "openid email email:change")).data.access_token;
    const bVerify = await postWithJson({
      url: `${backendUrl}/${ctx.tenantId}/v1/me/email/change/${transactionId}/verify`,
      headers: createBearerHeader(bToken),
      body: { verification_code: code },
    });
    console.log("cross-user verify:", bVerify.status, JSON.stringify(bVerify.data));
    expect(bVerify.status).toBe(404);

    // A's transaction is untouched, so A can still complete it.
    const aVerify = await postWithJson({
      url: `${backendUrl}/${ctx.tenantId}/v1/me/email/change/${transactionId}/verify`,
      headers: createBearerHeader(aToken),
      body: { verification_code: code },
    });
    expect(aVerify.status).toBe(200);
  });

  it("security: rejects a malformed new_email before any code is sent", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);
    const accessToken = (
      await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid email email:change")
    ).data.access_token;

    // new_email is committed verbatim as email and (EMAIL policy) as preferred_username, so a
    // free-form string must never reach the sender or the user record.
    // Non-string values must be rejected by the schema, not coerced by optValueAsString.
    for (const newEmail of [
      "not-an-email",
      "no-domain@",
      "@no-local.example.com",
      "a b@c.example.com",
      "",
      12345,
      { a: 1 },
      ["x"],
      null,
      true,
    ]) {
      const startResp = await postWithJson({
        url: `${backendUrl}/${ctx.tenantId}/v1/me/email/change`,
        headers: createBearerHeader(accessToken),
        body: { new_email: newEmail },
      });
      console.log("malformed new_email:", JSON.stringify(newEmail), startResp.status);
      expect(startResp.status).toBe(400);
      expect(startResp.data.error_description).toContain("invalid format");
    }

    // Missing entirely is rejected the same way.
    const missingResp = await postWithJson({
      url: `${backendUrl}/${ctx.tenantId}/v1/me/email/change`,
      headers: createBearerHeader(accessToken),
      body: {},
    });
    expect(missingResp.status).toBe(400);

    // The account is untouched.
    const userinfoResp = await getUserinfo({
      endpoint: `${backendUrl}/${ctx.tenantId}/v1/userinfo`,
      authorizationHeader: createBearerHeader(accessToken),
    });
    expect(userinfoResp.data.email).toBe(ctx.adminEmail);
  });

  it("security: the generic MFA minter refuses to mint an email-confirm flow", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);

    // POST /v1/me/mfa/{type} takes the flow from the URL path and enforces no scope. If it could
    // mint flow=email-change, the flow guard in the interactors would be powerless: the persisted
    // transaction is indistinguishable from one the scope-gated endpoint created.
    const plainToken = (await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid")).data
      .access_token;

    for (const flow of ["email-change", "email-verify"]) {
      const resp = await postWithJson({
        url: `${backendUrl}/${ctx.tenantId}/v1/me/mfa/${flow}`,
        headers: createBearerHeader(plainToken),
        body: {},
      });
      console.log(`mfa minter ${flow}:`, resp.status, JSON.stringify(resp.data));
      expect(resp.status).toBe(400);
      expect(resp.data.error_description).toContain("not an MFA operation");
      expect(resp.data.id).toBeUndefined();
    }

    // The account is untouched and the original address still logs in.
    expect((await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword)).status).toBe(200);
  });

  it("security: an email-change transaction cannot be committed through the verification endpoint", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);

    // Start a change with a properly scoped token, then try to finish it on the sibling URL, whose
    // scope requirement is only openid. The scope is checked against the URL's flow, so the commit
    // must additionally require the transaction's flow to match.
    const scopedToken = (
      await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid email email:change")
    ).data.access_token;
    const started = await startChange(ctx, scopedToken, `cross-${Date.now()}@me-change.example.com`);

    const plainToken = (await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid")).data
      .access_token;
    const crossed = await postWithJson({
      url: `${backendUrl}/${ctx.tenantId}/v1/me/email/verification/${started.transactionId}/verify`,
      headers: createBearerHeader(plainToken),
      body: { verification_code: started.code },
    });
    console.log("cross-flow commit:", crossed.status, JSON.stringify(crossed.data));
    expect(crossed.status).toBe(404);

    // Untouched: the original address is still the login identifier, and the owner can still finish
    // the change on the correct endpoint.
    expect((await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword)).status).toBe(200);
    const proper = await submitCode(ctx, scopedToken, started.transactionId, started.code);
    expect(proper.status).toBe(200);
  });

  it("security: the generic MFA minter refuses non-MFA flows even when a policy exists", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);

    // Register oauth/ciba policies first: without them the minter 404s on the policy lookup, which
    // would hide whether the flow itself is refused. With them, an unguarded minter returns 200 and
    // the resulting orphan transaction (empty AuthorizationIdentifier) 500s when driven.
    const loginPolicy = (flow) => ({
      id: uuidv4(),
      flow,
      enabled: true,
      policies: [
        {
          description: "password_login",
          priority: 1,
          conditions: {},
          available_methods: ["password"],
          step_definitions: [{ method: "password", order: 1, requires_user: false }],
          success_conditions: {
            any_of: [
              [
                {
                  path: "$.password-authentication.success_count",
                  type: "integer",
                  operation: "gte",
                  value: 1,
                },
              ],
            ],
          },
        },
      ],
    });

    for (const flow of ["oauth", "ciba"]) {
      const policyResp = await postWithJson({
        url: `${backendUrl}/v1/management/organizations/${ctx.organizationId}/tenants/${ctx.tenantId}/authentication-policies`,
        headers: { Authorization: `Bearer ${ctx.mgmtAccessToken}` },
        body: loginPolicy(flow),
      });
      expect(policyResp.status).toBe(201);
    }

    const token = (
      await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid email email:change")
    ).data.access_token;

    for (const flow of ["oauth", "ciba"]) {
      const resp = await postWithJson({
        url: `${backendUrl}/${ctx.tenantId}/v1/me/mfa/${flow}`,
        headers: createBearerHeader(token),
        body: {},
      });
      console.log(`mfa minter ${flow}:`, resp.status, JSON.stringify(resp.data));
      expect(resp.status).toBe(400);
      expect(resp.data.error_description).toContain("not an MFA operation");
      expect(resp.data.id).toBeUndefined();
    }
  });

  it("audit: emits a security event for a successful email change", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);
    const token = (
      await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid email email:change")
    ).data.access_token;

    const verifyResp = await runEmailChange(
      ctx,
      token,
      `audit-${Date.now()}@me-change.example.com`
    );
    expect(verifyResp.status).toBe(200);

    // Security events are published asynchronously.
    await new Promise((resolve) => setTimeout(resolve, 2000));

    const events = await get({
      url: `${backendUrl}/v1/management/organizations/${ctx.organizationId}/tenants/${ctx.tenantId}/security-events`,
      headers: { Authorization: `Bearer ${ctx.mgmtAccessToken}` },
      params: { limit: 30 },
    });
    expect(events.status).toBe(200);
    const types = events.data.list.map((e) => e.type);
    console.log("event types after change:", JSON.stringify(types));
    // Dedicated identifier-change events (not the generic login email-verification ones) so the
    // audit log can distinguish an email change from a login-time email verification.
    expect(types).toContain("email_change_success");
    expect(types).toContain("email_change_request_success");
  });

  it("concurrency: concurrent changes to the same email yield at most one success", async () => {
    const ctx = await provisionTenant(systemAccessToken, "EMAIL");
    tenants.push(ctx);
    const target = `race-${Date.now()}@me-change.example.com`;

    const bEmail = `raceb-${Date.now()}@me-change.example.com`;
    const bPassword = "RaceBPass_1!";
    await createUser(ctx, { name: "Race B", email: bEmail, password: bPassword });

    const aToken = (
      await passwordGrant(ctx, ctx.adminEmail, ctx.adminPassword, "openid email email:change")
    ).data.access_token;
    const bToken = (await passwordGrant(ctx, bEmail, bPassword, "openid email email:change")).data.access_token;

    // Two users start a change to the same target and read their codes.
    const a = await startChange(ctx, aToken, target);
    const b = await startChange(ctx, bToken, target);

    // Verify both concurrently: the uk_preferred_username constraint must let at most one commit.
    const [ra, rb] = await Promise.all([
      submitCode(ctx, aToken, a.transactionId, a.code),
      submitCode(ctx, bToken, b.transactionId, b.code),
    ]);
    console.log("race statuses:", ra.status, rb.status);
    const successes = [ra, rb].filter((r) => r.status === 200);
    expect(successes).toHaveLength(1);

    // The loser must lose cleanly: a duplicate is a client error (400 from the pre-check, 409 if
    // the uk_preferred_username constraint is what caught it), never a 500.
    const loser = [ra, rb].find((r) => r.status !== 200);
    console.log("race loser:", loser.status, JSON.stringify(loser.data));
    expect([400, 409]).toContain(loser.status);
  });

  it("USERNAME policy: allows changing to a duplicate email (email is not the identifier)", async () => {
    const ctx = await provisionTenant(systemAccessToken, "USERNAME");
    tenants.push(ctx);

    const otherEmail = `shared-${Date.now()}@me-change.example.com`;
    await createUser(ctx, { name: `other-${Date.now()}`, email: otherEmail, password: "OtherPass_1!" });

    // admin logs in by username (name), since the identity policy keys on USERNAME.
    const token = await passwordGrant(ctx, ctx.adminName, ctx.adminPassword, "openid email email:change");
    expect(token.status).toBe(200);
    const accessToken = token.data.access_token;

    const verifyResp = await runEmailChange(ctx, accessToken, otherEmail);
    console.log("duplicate(username) verify:", verifyResp.status, JSON.stringify(verifyResp.data));
    expect(verifyResp.status).toBe(200);

    const userinfoResp = await getUserinfo({
      endpoint: `${backendUrl}/${ctx.tenantId}/v1/userinfo`,
      authorizationHeader: createBearerHeader(accessToken),
    });
    expect(userinfoResp.data.email).toBe(otherEmail);

    // Login identifier is still the username, unchanged by the email edit.
    expect((await passwordGrant(ctx, ctx.adminName, ctx.adminPassword)).status).toBe(200);
  });
});
