apiVersion: v1
kind: Secret
metadata:
  name: idp-secrets
  namespace: idp
type: Opaque
stringData:
  POSTGRES_PASSWORD: "local-pg-password"
  DB_OWNER_PASSWORD: "local-owner-password"
  IDP_DB_ADMIN_PASSWORD: "local-admin-password"
  IDP_DB_APP_PASSWORD: "local-app-password"
  IDP_SERVER_API_KEY: "30113151-4ee1-4f6a-a1ac-cc1be9eaf695"
  IDP_SERVER_API_SECRET: "MTY5YjM3NmYtOTY0ZC00Nzg0LWIyOTMtOWQyNDhjMTkyNmIwCg=="
  ENCRYPTION_KEY: "JjN9c6N4STeA+g9d+TtBGp5MC3sbqOWs+S9qzJG42iY="
