package org.idp.server.core.mfa;

public enum StandardMfaInteractionType {
  PASSWORD_REGISTRATION,
  PASSWORD_AUTHENTICATION,
  EMAIL_VERIFICATION_CHALLENGE,
  EMAIL_VERIFICATION,
  WEBAUTHN_REGISTRATION_CHALLENGE,
  WEBAUTHN_REGISTRATION,
  WEBAUTHN_AUTHENTICATION_CHALLENGE,
  WEBAUTHN_AUTHENTICATION,
  FEDERATION_REQUEST,
  FEDERATION_CALLBACK;

  public MfaInteractionType toType() {
    return new MfaInteractionType(name());
  }
}
