// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import("@docusaurus/plugin-content-docs").SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  docs: [
    'introduction',
    {
      type: "category",
      label: "製品紹介",
      collapsed: false,
      items: [
        "content_01_intro/tech-overview",
        "content_01_intro/features",
        "content_01_intro/use-cases"
      ]
    },
    {
      type: "category",
      label: "クイックスタート",
      collapsed: false,
      items: [
        "content_02_quickstart/getting-started",
        "content_02_quickstart/setting-templates"
      ]
    },
    {
      type: "category",
      label: "コア概念",
      collapsed: false,
      items: [
        "content_03_concepts/multi-tenant",
        "content_03_concepts/id-management",
        "content_03_concepts/id-verified",
        "content_03_concepts/enterprise-id",
        {
          type: "category",
          label: "基礎（読み物）",
          items: [{ type: "autogenerated", dirName: "content_03_concepts/basic" }]
        }
      ]
    },
    {
      type: "category",
      label: "認可プロトコル",
      collapsed: false,
      items: [
        "content_04_protocols/authorization-code-flow",
        "content_04_protocols/ciba-flow"
      ]
    },
    {
      type: "category",
      label: "How-to（設定・運用レシピ）",
      collapsed: false,
      items: [
        "content_05_how-to/identity-verification-application",
        "content_05_how-to/identity-verification-application-guide",
        "content_05_how-to/identity-verification-registration",
        "content_05_how-to/mfa-fido-uaf-registration",
        "content_05_how-to/mfa-fido-uaf-deregistration",
        "content_05_how-to/ciba-flow-fido-uaf",
        "content_05_how-to/token-strategy"
      ]
    },
    {
      type: "category",
      label: "Developer Guide",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "実装ガイド",
          items: [{ type: "autogenerated", dirName: "content_06_developer-guide/developer-guide" }]
        },
        {
          type: "category",
          label: "設定ガイド",
          items: [{ type: "autogenerated", dirName: "content_06_developer-guide/configuration" }]
        },
        {
          type: "category",
          label: "拡張ガイド",
          items: [{ type: "autogenerated", dirName: "content_06_developer-guide/extension" }]
        }
      ]
    },
    {
      type: "category",
      label: "リファレンス",
      collapsed: false,
      items: [
        "content_07_reference/api-reference",
      ]
    },
    {
      type: "category",
      label: "運用（Ops）",
      collapsed: false,
      items: [
        "content_09_project/test-strategy",
        "content_08_ops/performance-test",
        "content_08_ops/deployment",
        {
          type: "category",
          label: "商用デプロイ",
          items: [{ type: "autogenerated", dirName: "content_08_ops/commercial-deployment" }]
        }
      ]
    },
    {
      type: "category",
      label: "プロジェクト",
      collapsed: false,
      items: [
        "content_09_project/faq",
        "content_09_project/roadmap",
        "content_09_project/contributing",
        "content_09_project/license"
      ]
    }
  ]
};

export default sidebars;
