// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    'introduction',
    'getting-started',
    'features',
    'use-cases',
    'multi-tenant',
    'setting-templates',
    'authorization-code-flow',
    'ciba-flow',
    'id-management',
    'id-verified',
    'identity-verification-application',
    `identity-verification-registration`,
    `mfa-fido-uaf-registration`,
    `mfa-fido-uaf-deregistration`,
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'configuration/authn/initial-registration',
        'configuration/authn/password',
        'configuration/authn/sms',
        'configuration/authn/email',
        'configuration/authn/fido-uaf',
        'configuration/authn/webauthn',
        'configuration/authn/authentication-device',
        'configuration/authn/legacy',
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      items: [
        'developer-guide/design-principles-guidelines',
        'developer-guide/dependency-injection',
        'developer-guide/multi-datasource',
        'developer-guide/transaction',
        'developer-guide/authentication-policy',
        'developer-guide/id-token-structure',
        'developer-guide/federation',
        'developer-guide/events',
        'developer-guide/security-event-hooks',
        'developer-guide/user-lifecycle-event',
        'developer-guide/caching',
      ],
    },
    'test-strategy',
    'deployment',
    'contributing',
    'faq',
    'roadmap',
    {
      type: 'doc',
      id: 'license', // docs/license.md
    },
  ],
};

export default sidebars;
