// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import("@docusaurus/plugin-content-docs").SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  docs: [
    'introduction',
    'document-index',
    {
      type: "category",
      label: "製品紹介",
      collapsed: true,
      items: [
        "content_01_intro/intro-01-tech-overview",
        "content_01_intro/intro-02-features",
        "content_01_intro/intro-03-use-cases"
      ]
    },
    {
      type: "category",
      label: "クイックスタート",
      collapsed: true,
      items: [
        "content_02_quickstart/quickstart-01-getting-started",
        "content_02_quickstart/quickstart-02-setting-templates"
      ]
    },
    {
      type: "category",
      label: "コア概念",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "基盤概念",
          collapsed: true,
          items: [
            "content_03_concepts/foundation/concept-01-multi-tenant",
            "content_03_concepts/foundation/concept-02-control-plane",
            "content_03_concepts/foundation/concept-03-client",
          ]
        },
        {
          type: "category",
          label: "アイデンティティ管理",
          collapsed: true,
          items: [
            "content_03_concepts/identity-management/concept-01-id-management",
            "content_03_concepts/identity-management/concept-02-password-policy",
          ]
        },
        {
          type: "category",
          label: "認証・認可",
          collapsed: true,
          items: [
            "content_03_concepts/authentication-authorization/concept-01-authentication-policy",
            "content_03_concepts/authentication-authorization/concept-02-mfa",
            "content_03_concepts/authentication-authorization/concept-03-session-management",
            "content_03_concepts/authentication-authorization/concept-04-authorization",
            "content_03_concepts/authentication-authorization/concept-05-grant-management",
            "content_03_concepts/authentication-authorization/concept-06-fapi",
            "content_03_concepts/authentication-authorization/concept-07-passwordless",
            "content_03_concepts/authentication-authorization/concept-08-federation",
          ]
        },
        {
          type: "category",
          label: "トークン・クレーム",
          collapsed: true,
          items: [
            "content_03_concepts/tokens-claims/concept-01-id-token",
            "content_03_concepts/tokens-claims/concept-02-token-management",
            "content_03_concepts/tokens-claims/concept-03-custom-claims",
          ]
        },
        {
          type: "category",
          label: "高度なID機能",
          collapsed: true,
          items: [
            "content_03_concepts/advanced-id/concept-01-id-verified",
            "content_03_concepts/advanced-id/concept-02-enterprise-id",
          ]
        },
        {
          type: "category",
          label: "セキュリティ・拡張",
          collapsed: true,
          items: [
            "content_03_concepts/security-extensions/concept-01-security-events",
            "content_03_concepts/security-extensions/concept-02-external-service-integration",
            "content_03_concepts/security-extensions/concept-03-schema-validation",
          ]
        },
        {
          type: "category",
          label: "運用・監視",
          collapsed: true,
          items: [
            "content_03_concepts/operations/concept-01-audit-compliance",
            "content_03_concepts/operations/concept-02-application-logging",
            "content_03_concepts/operations/concept-03-tenant-statistics",
            "content_03_concepts/operations/concept-04-operations",
          ]
        },
        {
          type: "category",
          label: "基礎（読み物）",
          items: [{ type: "autogenerated", dirName: "content_03_concepts/basic" }]
        }
      ]
    },
    {
      type: "category",
      label: "認証・認可プロトコル",
      collapsed: true,
      items: [
        "content_04_protocols/protocol-01-authorization-code-flow",
        "content_04_protocols/protocol-02-ciba-flow",
        "content_04_protocols/protocol-03-introspection",
        "content_04_protocols/protocol-04-ciba-rar",
        "content_04_protocols/protocol-05-fapi-ciba"
      ]
    },
    {
      type: "category",
      label: "How-to（設定・運用レシピ）",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "content_05_how-to" }]
    },
    {
      type: "category",
      label: "Developer Guide",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Getting Started",
          items: [{ type: "autogenerated", dirName: "content_06_developer-guide/01-getting-started" }]
        },
        {
          type: "category",
          label: "Control Plane（管理API）",
          items: [{ type: "autogenerated", dirName: "content_06_developer-guide/02-control-plane" }]
        },
        {
          type: "category",
          label: "Application Plane（認証・認可API）",
          items: [{ type: "autogenerated", dirName: "content_06_developer-guide/03-application-plane" }]
        },
        {
          type: "category",
          label: "Implementation Guides（実装ガイド）",
          items: [{ type: "autogenerated", dirName: "content_06_developer-guide/04-implementation-guides" }]
        },
        {
          type: "category",
          label: "Configuration（設定）",
          items: [{ type: "autogenerated", dirName: "content_06_developer-guide/05-configuration" }]
        },
        {
          type: "category",
          label: "Patterns（実装パターン）",
          items: [{ type: "autogenerated", dirName: "content_06_developer-guide/06-patterns" }]
        },
        {
          type: "category",
          label: "Troubleshooting（トラブルシューティング）",
          items: [{ type: "autogenerated", dirName: "content_06_developer-guide/07-troubleshooting" }]
        },
        {
          type: "category",
          label: "Reference（リファレンス）",
          items: [{ type: "autogenerated", dirName: "content_06_developer-guide/08-reference" }]
        },
        {
          type: "category",
          label: "Learning Paths（学習パス）",
          items: [{ type: "autogenerated", dirName: "content_06_developer-guide/learning-paths" }]
        }
      ]
    },
    {
      type: "category",
      label: "リファレンス",
      collapsed: true,
      items: [
        "content_07_reference/api-reference",
      ]
    },
    {
      type: "category",
      label: "運用（Ops）",
      collapsed: true,
      items: [
        "content_08_ops/ops-01-test-strategy",
        "content_08_ops/ops-02-performance-test",
        {
          type: "category",
          label: "商用デプロイ",
          items: [{ type: "autogenerated", dirName: "content_08_ops/commercial-deployment" }]
        }
      ]
    },
    {
      type: "category",
      label: "プロジェクト",
      collapsed: true,
      items: [
        "content_09_project/project-01-faq",
        "content_09_project/project-02-roadmap",
        "content_09_project/project-03-contributing",
        "content_09_project/project-04-license"
      ]
    },
    {
      type: "category",
      label: "AI",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "content_10_ai_developer" }]
    }
  ]
};

export default sidebars;
