name: AI Code Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: "gpt-4o" # Optional: defaults to "gpt-4"
          PROMPT: |
            You are a senior engineer.Please actively review any areas for improvement you find to make the code easier for everyone to read.
            Please point out any excellent points.
            Since the code given to you is only a portion of it, please be reluctant to point out undefined methods or classes.
            Please be reluctant to point out comments that express WHAT.
            First, Please review the PR as a whole.　Then, comment on each problematic piece of code.
            Second, when pointing out an issue, please explain the reason for the change and provide an example of the changed code.
            Please point out the following points in particular:
              - Are there any violations of design principles?
              - Are there any names that are misleading or do not accurately represent the actual situation?
              - Are variables defined at the appropriate granularity?
              - Are methods and functions divided at the appropriate granularity?
              - Is there any redundant code?
              - Is there any part that causes the N+1 problem?
              - Are the WHY comments properly written?
              - Are there any complex conditional expressions created?
              - Are there any obvious security issues?
